language: node_js

node_js:
  - "8"
  - "10"
  - "12"

os:
  - linux
  - osx
  - windows

jobs:
  include:
    - os: linux
      node_js: "12"
      services:
        - docker
      install:
        - npm install
        - npm run build
        - npm install -g aurelia-cli
      script:
        - au new second -u -s http2,typescript,htmlmin-min,less,postcss-typical,jest,protractor,scaffold-navigation,docker && cd ./second && npm install && npm link aurelia-cli && npm run docker:build
    - os: linux
      node_js: "10"
      services:
        - docker
      install:
        - npm install
        - npm run build
        - npm install -g aurelia-cli
      script:
        - au new second -u -s http2,typescript,htmlmin-min,less,postcss-typical,jest,protractor,scaffold-navigation,docker && cd ./second && npm install && npm link aurelia-cli && npm run docker:build
    - os: linux
      node_js: "8"
      services:
        - docker
      install:
        - npm install
        - npm run build
        - npm install -g aurelia-cli
      script:
        - au new second -u -s http2,typescript,htmlmin-min,less,postcss-typical,jest,protractor,scaffold-navigation,docker && cd ./second && npm install && npm link aurelia-cli && npm run docker:build
