os:
  - linux
  - windows
  - osx
language: node_js
node_js:
  - "8"
  - "10"
  - "12"

install:
  - npm install
  - npm run build

script:
  - au new second -u -s http2,typescript,htmlmin-min,less,postcss-typical,jest,protractor,scaffold-navigation,docker && cd ./second && npm install && npm link aurelia-cli && npm run docker:build
