version: '1.1.2.{build}'
image: Windows Server 2019

environment:
  nodejs_version: "12"
platform:
  - Any CPU

init:
  - ps: git config --global core.autocrlf input


# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - docker version
  - node --version
  - npm --version

before_build:
  - npm run test

build_script:
  - npm run build
  - npm link

test_script:
  - ps: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
  - docker-switch-linux
  - au new sixth -u -s cli-bundler,alameda,http2,typescript,htmlmin-min,less,postcss-typical,jest,protractor,scaffold-navigation,docker
  - cd ./sixth
  - npm install
  - npm link aurelia-cli
  - npm run docker:build
cache:
  - '%APPDATA%\npm-cache'

on_success:
  - ps: Write-Host "All Done" -ForegroundColor DarkGreen -BackgroundColor White
