version: "3.7"

services:
  /* @echo projectName */:
    image: /* @echo projectName */:0.1.0
    build:
      context: . # relative to docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    restart: unless-stopped
